[package]
name = "wolkenwelten-client"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
anyhow = "1.0.66"
bytemuck = "1.12.2"
tokio = { version = "1.21.2", features = ["full"] }
winit = "0.27.5"
wgpu = "0.14.0"
glam = "0.22.0"
tobj = "3.2.3"
image = { version = "0.24.4", default-features = false, features = ["png"]}
wolkenwelten-common = { path = "../common" }
wolkenwelten-game = { path = "../game" }
wolkenwelten-meshgen = { path = "../meshgen" }
