[package]
name = "rostregen"
version = "0.0.1"
edition = "2021"

[dependencies]
winit = "0.27.4"
glutin = "0.29.1"
rand = "0.8.5"
gl = "0.14.0"
glam = "0.21.3"
tobj = "3.2.3"
image = { version = "0.24.4", default-features = false, features = ["png"]}
#deno_core = "0.154.0"
#deno_ops = "0.32.0"
#v8 = "0.52.0"
#rapier3d = "0.15.0"
