[package]
name = "rostregen"
version = "0.0.1"
edition = "2021"

[dependencies]
sdl2 = "0.35.2"
gl = "0.10.0"
glam = "0.21.3"
tobj = "3.2.3"
image = { version = "0.24.4", default-features = false, features = ["png"]}