[package]
name = "wolkenwelten"
version = "0.0.2"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"
authors = ["Benjamin Vincent Schulenburg <ben@wolkenwelten.net>"]
description = """
An open voxel sandbox
"""

[dependencies]
glam = { version = "0.22", features = ["bytemuck", "serde"] }
glium = "0.32"
winit = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wolkenwelten-client = { path = "client" }
wolkenwelten-common = { path = "common" }
wolkenwelten-game = { path = "game" }
wolkenwelten-meshgen = { path = "meshgen" }
wolkenwelten-scripting = { path = "scripting" }
wolkenwelten-sound = { path = "sound" }
wolkenwelten-particles = { path = "particles" }
wolkenwelten-input-winit = { path = "input_winit" }

[profile.dev]
opt-level = 2
lto = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[features]
default = ["client"]
client = []
