[package]
name = "wolkenwelten"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"
authors = ["Benjamin Vincent Schulenburg <ben@wolkenwelten.net>"]
description = """
An open voxel sandbox
"""

[dependencies]
glutin = "0.29.1"
gl = "0.14.0"
#deno_core = "0.154.0"
#deno_ops = "0.32.0"
#v8 = "0.52.0"
#rapier3d = "0.15.0"

[features]
default = ["client"]
client = []

[dependencies.wolkenwelten-client]
path = "client"

[dependencies.wolkenwelten-game]
path = "game"

[workspace]
members = [
    "./",
    "game",
    "client",
]
default-members = [
    "./",
    "game",
    "client",
]
