[package]
name = "wolkenwelten"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"
authors = ["Benjamin Vincent Schulenburg <ben@wolkenwelten.net>"]
description = """
An open voxel sandbox
"""

[dependencies]
glutin = "0.29.1"
gl = "0.14.0"
winit = "0.27.5"

[features]
default = ["client"]
client = []

[dependencies.wolkenwelten-client]
path = "client"

[dependencies.wolkenwelten-game]
path = "game"

[dependencies.wolkenwelten-meshgen]
path = "meshgen"

[dependencies.wolkenwelten-scripting]
path = "scripting"

[dependencies.wolkenwelten-sound]
path = "sound"

[workspace]
members = [
    "./",
    "game",
    "client",
    "meshgen",
    "scripting",
    "sound",
]
default-members = [
    "./",
    "game",
    "client",
    "meshgen",
    "scripting",
    "sound",
]
