[package]
name = "wolkenwelten-common"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
rgb = "0.8.34"
glam = "0.22"
rand = "0.8"
rand_chacha = "0.3"