[package]
name = "wolkenwelten-particles"
version = "0.0.2"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
palette = "0.6"
rgb = "0.8"
glium = "0.32"
glam = "0.22"
rand = "0.8"
rand_xorshift = "0.3"
wolkenwelten-common = { path = "../common" }

