[package]
name = "wolkenwelten-particles"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
glium = "0.32.1"
glam = "0.22.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
wolkenwelten-common = { path = "../common" }

