[package]
name = "wolkenwelten-meshgen"
version = "0.0.3"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
glium = "0.32"
wolkenwelten-common = { path = "../common" }

