name: WolkenWelten Checks

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  checks:
    name: Check formatting / clippy / testsuit
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install additional dependencies
      run: sudo apt-get -y install libasound2-dev libfontconfig1-dev libfreetype6-dev

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Run cargo fmt
      run: cargo fmt --all --check

    - name: Run clippy
      run: cargo clippy --no-deps

    - name: Run testsuite
      run: cargo test

