name: WolkenWelten CI

on:
  push:
  pull_request:

jobs:
  cargo-fmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run cargo fmt
      run: cargo fmt --all --check
  cargo-clippy:
    name: Check code with clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run clippy
        run: cargo clippy
  cargo-test:
    name: Run testsuite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run testsuite
      run: cargo test

