name: WolkenWelten CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  fmt:
    name: Check formatting / clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install additional dependencies
      run: sudo apt-get -y install libasound2-dev libfontconfig1-dev libfreetype6-dev

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Run cargo fmt
      run: cargo fmt --all --check

    - name: Run clippy
      run: cargo clippy --no-deps

  test:
    name: Run tests - ${{ matrix.rust }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install additional dependencies
      run: sudo apt-get -y install libasound2-dev libfontconfig1-dev libfreetype6-dev

    - name: Install toolchain
      run: rustup default ${{ matrix.rust }}

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Run testsuite
      run: cargo test

  release:
    name: Build release - ${{ matrix.os }}
    needs: [fmt, test]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      CARGO_TERM_COLOR: always
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [x86_64-linux, x86_64-macos, x86_64-windows] #, aarch64-linux, x86_64-win-gnu, win32-msvc
        include:
        - build: x86_64-linux
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: x86_64-macos
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
        - build: x86_64-windows
          os: windows-2019
          rust: stable
          target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install additional dependencies
        if: matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux'
        run: sudo apt-get -y install libasound2-dev libfontconfig1-dev libfreetype6-dev

      - uses: Swatinem/rust-cache@v2

      - name: Build release (Linux)
        if: matrix.build == 'x86_64-linux' || matrix.build == 'aarch64-linux'
        run: bash tools/build-linux/build.sh

      - name: Build release (MacOS)
        if: matrix.build == 'x86_64-macos' || matrix.build == 'aarch64-macos'
        run: bash tools/build-macos/build.sh

      - name: Build release (Windows)
        if: matrix.build == 'x86_64-windows' || matrix.build == 'aarch64-windows'
        run: bash tools/build-windows/build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.build }}
          path: dist/

