[package]
name = "wolkenwelten-scripting"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
deno_core = "0.156.0"
deno_ops = "0.34.0"

[dependencies.wolkenwelten-game]
path = "../game"
