[package]
name = "wolkenwelten-scripting"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://wolkenwelten.net"

[dependencies]
deno_core = "0.156.0"
deno_ops = "0.34.0"

[build-dependencies]
anyhow = "1.0.66"
swc = "0.232.61"
swc_common = "0.29.12"
swc_ecma_parser = { version = "0.122.22", features = ["typescript"] }
